name: "Manual build"

on:
  workflow_dispatch:
    inputs:
      butler_version:
        description: Butler version
        type: string
        required: true
        default: "15.21.0"

env:
  IMAGE_NAME: butler

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo IMAGE_OWNER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV
      - uses: actions/checkout@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ env.IMAGE_OWNER }}/${{ github.repository.name }}:${{ inputs.butler_version }}
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ inputs.butler_version }}
          build-args: BUTLER_VERSION=${{ inputs.butler_version }}
